# Generated by Django 5.2.5 on 2025-08-26 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_add_sample_data'),
    ]

    operations = [
    ]
