# Generated by Django 5.2.5 on 2025-08-27 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_sample_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog_images/additional/')),
                ('caption', models.CharField(blank=True, help_text='Optional caption for this image', max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which this image should appear')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='posts.blogpost')),
            ],
            options={
                'verbose_name': 'Additional Blog Image',
                'verbose_name_plural': 'Additional Blog Images',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
    ]
